spring:
  datasource:
    url: jdbc:postgresql://antonio-dev.go.ro:15770/autoflexdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    drop-first: false # Drops and creates scheme from scratch on every start
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://antonio-dev.go.ro:8081/keycloak-app/realms/floral-elegance-realm

keycloak:
  realm: floral-elegance-realm
  resource: floral-elegance-backend
  # auth-server-url: http://antonio-dev.go.ro:8081/keycloack-app/realms/gym-management-realm/protocol/openid-connect/auth
  auth-server-url: http://antonio-dev.go.ro:8081/keycloak-app/
  credentials:
    secret: cVVyk0VfUHGDYdmjIAdYTE9LWO162sOP
  admin:
    username: admin
    password: admin

cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
